Fix ARMv8 target used for accelerated CRC32 instructions
We always build zlib-ng with support for hardware-accelerated CRC32
because it checks for CRC32 instruction availability at runtime and
changes the active implementation accordingly. However, building for
devices where CRC32 support has not been declared (i.e. armv8-a or
generic architecture and CPU targets respectively) fails with the
following error:

fatal error: error in backend: Cannot select: intrinsic %llvm.aarch64.crc32w
PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: prebuilts/clang/host/linux-x86/clang-r416183/bin/clang.real -c -Wno-enum-compare -Wno-enum-compare-switch -Wno-null-pointer-arithmetic -Wno-null-dereference -Wno-pointer-compare -Wno-xor-used-as-pow -Wno-final-dtor-non-final-class -Wno-psabi -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -Werror=date-time -Werror=pragma-pack -Werror=pragma-pack-suspicious-include -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -fcommon -Werror=int-conversion -fexperimental-new-pass-manager -Wno-reserved-id-macro -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-gnu-folding-constant -Wno-compound-token-split-by-macro -ftrivial-auto-var-init=zero -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=format-security -nostdlibinc -march=armv8-a -target aarch64-linux-android10000 -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin -fPIC -Iexternal/zlib-ng -Iexternal/zlib-ng -D__LIBC_API__=10000 -D__LIBM_API__=10000 -D__LIBDL_API__=10000 -Ibionic/libc/include -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DZLIB_CONST -DWITH_GZFILEOP -DZLIB_COMPAT -DZLIB_DLL -D_LARGEFILE64_SOURCE=1 -D__USE_LARGEFILE64 -Wall -Werror -Wno-implicit-fallthrough -O3 -DNDEBUG -fno-semantic-interposition -std=c99 -DUNALIGNED_OK -DARM_ACLE_CRC_HASH -DARM_FEATURES -DARM_NEON_ADLER32 -DARM_NEON_CHUNKSET -DARM_NEON_SLIDEHASH -DUNALIGNED64_OK -std=gnu99 -Isystem/core/include -Isystem/media/audio/include -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include -Ihardware/ril/include -Iframeworks/native/include -Iframeworks/native/opengl/include -Iframeworks/av/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm64 -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -Ilibnativehelper/include_jni -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Wno-void-pointer-to-enum-cast -Wno-void-pointer-to-int-cast -Wno-pointer-to-int-cast -Werror=fortify-source -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-int-in-bool-context -Wno-sizeof-array-div -Wno-tautological-overlap-compare -Wno-deprecated-copy -Wno-range-loop-construct -Wno-misleading-indentation -Wno-zero-as-null-pointer-constant -Wno-deprecated-anon-enum-enum-conversion -Wno-deprecated-enum-enum-conversion -Wno-string-compare -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-pessimizing-move -Wno-non-c-typedef-for-linkage -Wno-string-concatenation -MD -MF out/soong/.intermediates/external/zlib-ng/libz/android_arm64_armv8-a_static/obj/external/zlib-ng/arch/arm/insert_string_acle.o.d -o out/soong/.intermediates/external/zlib-ng/libz/android_arm64_armv8-a_static/obj/external/zlib-ng/arch/arm/insert_string_acle.o external/zlib-ng/arch/arm/insert_string_acle.c
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'external/zlib-ng/arch/arm/insert_string_acle.c'.
4.	Running pass 'AArch64 Instruction Selection' on function '@quick_insert_string_acle'
 #0 0x0000000003fb9628 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (prebuilts/clang/host/linux-x86/clang-r416183/bin/clang.real+0x3fb9628)
 #1 0x0000000003fb94b0 llvm::sys::RunSignalHandlers() (prebuilts/clang/host/linux-x86/clang-r416183/bin/clang.real+0x3fb94b0)
 #2 0x0000000003f86193 (prebuilts/clang/host/linux-x86/clang-r416183/bin/clang.real+0x3f86193)
 #3 0x0000000003f8614b (prebuilts/clang/host/linux-x86/clang-r416183/bin/clang.real+0x3f8614b)
 #4 0x00000000038a8147 llvm::sys::Process::Exit(int, bool) (prebuilts/clang/host/linux-x86/clang-r416183/bin/clang.real+0x38a8147)
 #5 0x00000000038a80f0 (prebuilts/clang/host/linux-x86/clang-r416183/bin/clang.real+0x38a80f0)
 #6 0x0000000002489052 llvm::report_fatal_error(llvm::Twine const&, bool) (prebuilts/clang/host/linux-x86/clang-r416183/bin/clang.real+0x2489052)
 #7 0x00000000032d7948 (prebuilts/clang/host/linux-x86/clang-r416183/bin/clang.real+0x32d7948)
 #8 0x000000000247d157 llvm::SelectionDAGISel::CannotYetSelect(llvm::SDNode*) (prebuilts/clang/host/linux-x86/clang-r416183/bin/clang.real+0x247d157)
 #9 0x000000000245d006 llvm::SelectionDAGISel::SelectCodeCommon(llvm::SDNode*, unsigned char const*, unsigned int) (prebuilts/clang/host/linux-x86/clang-r416183/bin/clang.real+0x245d006)
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)

This is caused by forcing Clang to emit CRC32 instructions for a target
CPU that doesn't support them. Fix the issue by using
TARGET_ARMV8_WITH_CRC correctly in insert_string_acle.c, similar to how
it's used in crc32_acle.c.

Fixes: https://github.com/android/ndk/issues/1568